revise

diff --git a/.github/workflows/warn_on_files_changed.yml b/.github/workflows/warn_on_files_changed.yml
--- a/.github/workflows/warn_on_files_changed.yml
+++ b/.github/workflows/warn_on_files_changed.yml
@@ -19,6 +19,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+      # Do not `exit 1` — we don't want to report failed checks.
       - run: |
           for file in $(gh pr view ${{ github.event.number }} --json files -q '.files[].path'); do
             # -E is for extended pattern matching
@@ -27,7 +28,7 @@ jobs:
 
             # if grep returns 0, then the file contains the string
             if [ $? -eq 0 ]; then
-                exit 1;
+                echo "::set-output name=should_warn::1"
             fi
           done
         env:
@@ -36,7 +37,7 @@ jobs:
   post-pr-warning:
     runs-on: ubuntu-latest
     needs: [check-for-tfc-docs-changes]
-    if: always() && needs.check-for-tfc-docs-changes.result == 'failure'
+    if: needs.check-for-tfc-docs-changes.outputs.should_warn == '1'
     steps:
       - name: Echo if failed
         run: |
@@ -57,4 +58,3 @@ jobs:
             > If necessary reversions were already made, feel free to ignore this comment.
             >
             [^1]: For details on this particular workflow, see [${{github.workflow}}](${{github.server_url}}/${{github.repository}}/blob/main/${{github.workflow}})
-      - run: exit 0
